# -*- coding: utf-8 -*-
"""project 107

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjZ-BFti3EckSvPGTifvZDCD8IIimOcU
"""

#Project 107 , DATA ANALYSIS BY VISUALIZATION

from google.colab import files
data_to_load = files.upload()

import pandas as pd
import csv
import plotly.express as go

df = pd.read_csv("data.csv")

mean = df.groupby(["student_id", "level"], as_index=False)["attempt"].mean()

fig = go.scatter(mean, x="student_id", y="level", size="attempt", color="attempt")

fig.show()